### ISSUE TITLE
Import date makes all other tiles pale colors 

### ISSUE THREAD

**Issue by SuperSandro2000** [tieum/atuin-graph#5]
Obviously I imported my history on 14th June 2022 with quite some entries and because of that all other tiles are very light colors. Maybe this could be ignored, to make the other tiles darker colors, too.

![atuin-sandro](https://github.com/tieum/atuin-graph/assets/7258858/eb072d68-f201-4ccb-a28d-2d8300319a90)

**Comment by tieum** [comment]
Looking at https://github.com/ellie/atuin/issues/446#issuecomment-1151997295, if the imported file does not contain timestamp this is the expected behavior

What you can do is use the `--from` argument: ```atuin-graph --user USER --from 2022-06-15```

(`--from` argument is not in the readme yet but will show with `atuin-graph -h`)
