### ISSUE TITLE
sqlite option or ability?

### ISSUE THREAD

**Issue by poblabs** [tieum/atuin-graph#7]
hey there, this is great. found it while looking for this exact thing without using their servers. my setup is using sqlite. i know this is for postgres. is it possible to translate it to sqlite queries?

**Comment by poblabs** [comment]
I'm realizing that this is for the atuin self hosted server (which I'm not running). Instead I'm just using atuin and it's sqlite database. I was able to get the heatmap graph by modifying the [generate_calendar.py](https://github.com/tieum/atuin-graph/blob/main/atuin_graph/generate_calendar.py) and using this sqlite query 

`SELECT timestamp, count(timestamp) AS activity FROM history GROUP BY timestamp ORDER BY timestamp`

since I'm the only user, this is working well for me. Thanks for the project!

**Comment by vmdude** [comment]
Hi @poblabs, could you share the modified version of the `generate_calendar.py` you used for local sqlite query ? I'm interested as well, thanks :)

**Comment by poblabs** [comment]
> Hi @poblabs, could you share the modified version of the `generate_calendar.py` you used for local sqlite query ? I'm interested as well, thanks :)

Sure, I've attached it. I run the script hourly using cron. 

One thing to notice:

* You may want to remove this line: `df = df[df['timestamp'] >= 1689370971000000000]`. I added it because I didn't want to graph my lines prior to me installing atuin. 

The rest seems self-explanatory. 

[atuin_graph_bash_history.zip](https://github.com/tieum/atuin-graph/files/12833362/atuin_graph_bash_history.zip)

and here's my graph: 

![image](https://github.com/tieum/atuin-graph/assets/3484775/ef85dae4-b054-43ce-9821-3687340f20e3)
